### ISSUE TITLE
rpchost from bitcoin.conf not used

### ISSUE THREAD

**Issue by hawkmauk** [dcdpr/btcr-DID-method#27]
When defining parameters in a config file with txid2txref, the rpchost parameter is not used, instead the default 127.0.0.1 is.  The rpchost can be set in the command argument --rpchost=.

**Comment by hawkmauk** [comment]
I suspect that it's to do with this line here:
```opt->setCommandOption("rpchost");```
As this uses a different method to the other options that are working as expected.

I'll do some testing later, changing this to:
```opt->setOption("rpchost");```
Which I'm hoping will resolve the issue.

This code also appears across the other applications so I'll need to test it there too.  I'll have a look at the possibility of refactoring this to avoid duplication.

**Comment by danpape** [comment]
Thanks for the pull request!
